name: aura
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.6.0
  flutter_screenutil: ^5.9.3
  go_router: ^14.2.7
  flutter_svg: ^2.0.10+1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.2
  flutter_riverpod: ^2.5.1
  loading_animation_widget: ^1.2.1
  lottie: ^3.1.2
  flutter_remix: ^0.0.3
  ficonsax: ^0.0.3
  blobs: ^2.0.0
  flutter_animate: ^4.5.0
  fpdart: ^2.0.0-dev.3
  flutter_appauth: ^7.0.0
  crypto: ^3.0.5
  cached_network_image: ^3.4.1
  date_format: ^2.0.9
  fl_chart: ^0.69.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  infinite_scroll_pagination: ^4.0.0
  timeago: ^3.7.0
  timeago_flutter: ^3.7.0
  google_generative_ai: ^0.4.6
  icons_launcher: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/brand/
    - assets/animations/
    - assets/emojis/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
